In [1]:
import numpy as np

In [2]:
marks = [60,70,80,90]
print(marks)

[60, 70, 80, 90]


In [3]:
marks_np = np.array([60,70,80,90])
print(marks_np)

[60 70 80 90]


In [4]:
marks = [60,70,80,90]

new_marks = []

for mark in marks:
  new_marks.append(mark+5)

print(new_marks)

[65, 75, 85, 95]


In [5]:
marks_np = np.array([60,70,80,90])

print(marks_np + 5)

[65 75 85 95]


In [6]:
arr1 = np.array([10,20,30,40])
print(arr1)

[10 20 30 40]


In [7]:
arr2 = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr2)

[[10 20 30]
 [40 50 60]]


In [8]:
data = np.array([
    [2,60,45],
    [5,80,70],
    [8, 90, 85],
    [1, 40, 30]
])

print("Shape:", data.shape)
print("Size:", data.size)
print("Dimension:", data.ndim)
print("Data Type:", data.dtype)

Shape: (4, 3)
Size: 12
Dimension: 2
Data Type: int64


In [9]:
marks = np.array([45, 67, 89, 32, 76])

print(marks[0])
print(marks[-1])
print(marks[1:4])

45
76
[67 89 32]


In [12]:
marks = np.array([45,67,89,32,76,90])

print(np.mean(marks))
print(marks.max())
print(np.max(marks))

# max(), sum(), min(), median(), std()

66.5
90
90


In [15]:
arr = np.array([10, 20, "30"])

print(arr)
print(arr.dtype)

# print(arr + 5)

['10' '20' '30']
<U21


In [17]:
arr = np.array([10, 20, np.nan, 40])
print(np.mean(arr))
print(np.sum(arr))

nan
nan


In [ ]:
arr = np.array([])

In [19]:
a = np.array([10, 20, 30])
b = np.array([1, 2])



ValueError: operands could not be broadcast together with shapes (3,) (2,) 